### ISSUE TITLE
Add bash files

### ISSUE THREAD

**Issue by cmbengue-ec-intl** [ec-intl/dotfiles#12]
```[tasklist]
### Tasks
- [x] Add bash-src folder
- [x] Add bash aliases file
- [x] Add bash environment file
- [x] Add bash functions file
- [x] Update install-bashrc.sh file
```
