### ISSUE TITLE
Add zsh installation file

### ISSUE THREAD

**Issue by cmbengue-ec-intl** [ec-intl/dotfiles#13]
```[tasklist]
### Tasks
- [x] Add aliases file
- [x] Add environment file
- [x] Add function file
- [x] Update the installation file
```
